Anki flashcard export
Ankinator/ankinator-flashcard-models pull request #7
Opened 2023-06-27 20:55 UTC by SimonEndres

Können wir den mergen @lkno0705 ?

2023-06-28 08:14 UTC, Niklas-23 requested changes
No, this can definitely not be merged that way. Several things have gone wrong here:

1. We always use English on GitHub, please.
2. This PR contains commits from @pranav1305  and @SimonEndres . WHY WEREN'T DIFFERENT BRANCHES USED?
3. For each PR a jira ticket is created and the PR title contains the corresponding jira tag.

To solve this problem, one needs to copy out all T5 content from @pranav1305  and then delete it to create a clean PR. Then create a new branch and upload the T5 content there.

2023-06-28 08:16 UTC, lkno0705 requested changes
We can't merge it like this.. This PR is kind of a mess.
1. The corresponding link to the Backlogitem on Jira is missing
2. Why is the T5 model here? This should not be here. This should be a seperate Backlogitem with a corresponding branch.
3. The T5 model isn't finished yet
4. The train and validation pt files, shouldn't be versioned on git at all, as large files that are in a binary non human readable format will cause unnecessary problems
5. The T5 model notebook isn't saved in the chorrect folder structure either.

So, In terms of the data export and exploration part, this PR is fine.. but because of the rest, we can't merge it like that. Please remove the T5 stuff from this PR and Branch and move it to a second one, with a corresponding backlog item. Also the correct Backlogitem for this PR should be added. I'd suggest to create a new branch from main and copy the T5 stuff over and then deleting it from this branch with a new commit.

2023-06-28 08:16 UTC, lkno0705 commented on valid_data.pt
This should not be here

2023-06-28 08:16 UTC, lkno0705 commented on train_data.pt
This should also not be here

2023-06-28 08:16 UTC, lkno0705 commented on txt_models 2.ipynb
This should also not be here.. The T5 model has nothing to do with the flashcard analysis and export.. This should be on a seperate branch in a seperate Pull Request with a second backlog item linked to it...

2023-06-28 08:16 UTC, lkno0705 commented on notebooks/dataexploration/data_exploration.ipynb
For now this is ok, but we'll need to add some plots to this later, for the report

2023-07-03 13:51 UTC, lkno0705 approved these changes
lgtm

2023-07-03 15:07 UTC, Niklas-23 approved these changes
Now it looks good

2023-07-03 16:35 UTC, merged